# deployment Spring application
apiVersion: v1
kind: Service
metadata:
  name: springboot-postgres-k8s
  labels:
    name: springboot-postgres-k8s
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-postgres-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-postgres-k8s
spec:
  selector:
    matchLabels:
      app: springboot-postgres-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-postgres-k8s
    spec:
      containers:
        - name: springboot-postgres-k8s
          image: springboot-postgres-k8s:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres:5432/projectManager"
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "07022005"