apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: postgres-init
          image: postgres
          command:
            - /bin/bash
            - -c
            - |
              echo 'Waiting for postgres...'
              while ! pg_isready -h $(POSTGRES_HOST) -p 5432 -U postgres; do
                sleep 1
              done
              echo 'PostgreSQL is up - executing init script'
              PGPASSWORD=$(POSTGRES_PASSWORD) psql -h $(POSTGRES_HOST) -U postgres -d $(POSTGRES_DB) -f /init/init.sql
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
          volumeMounts:
            - name: init-script
              mountPath: /init
      volumes:
        - name: init-script
          configMap:
            name: postgres-conf
            items:
              - key: init.sql
                path: init.sql